# Generated by Django 4.1.3 on 2022-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbproject", "0003_sysuser_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("avatar", models.URLField(blank=True, max_length=256)),
                ("gender", models.CharField(default="男", max_length=10)),
                ("age", models.IntegerField(default=0)),
                ("phone", models.CharField(default="", max_length=20)),
                ("course", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
