# Generated by Django 4.1.3 on 2022-12-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dbproject", "0004_coach"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(default="", max_length=20)),
                ("course_begin", models.DateTimeField()),
                ("course_last", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="coach", name="course",),
        migrations.CreateModel(
            name="CourseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbproject.coach",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbproject.course",
                    ),
                ),
                (
                    "sys_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbproject.sysuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dbproject.coach"
            ),
        ),
    ]
