# Generated by Django 4.1.3 on 2022-12-18 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dbproject", "0005_course_remove_coach_course_courseorder_course_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseorder",
            name="created_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
