# Generated by Django 4.1.3 on 2022-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbproject", "0006_courseorder_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseorder",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
